### ISSUE TITLE
Upgrading from 1.0.3 to 1.0.5 - Argument 1 passed to craft\helpers\StringHelper::containsAny() must be of the type string, array given

### ISSUE THREAD

**Issue by john-henry** [fruitstudios/craft-searchit#11]
Craft: 3.1.8
Searchit: Upgrading from 1.0.3 to 1.0.5

```
TypeError: Argument 1 passed to craft\helpers\StringHelper::containsAny() must be of the type string, array given, called in ../vendor/fruitstudios/searchit/src/models/ElementFilter.php on line 94

Migration: fruitstudios\searchit\migrations\m190204_000001_source_to_uids

Output:

Exception: Argument 1 passed to craft\helpers\StringHelper::containsAny() must be of the type string, array given, called in ../vendor/fruitstudios/searchit/src/models/ElementFilter.php on line 94 (../vendor/craftcms/cms/src/helpers/StringHelper.php:91)
#0 ../vendor/fruitstudios/searchit/src/models/ElementFilter.php(94): craft\helpers\StringHelper::containsAny(Array, Array)
#1 [internal function]: fruitstudios\searchit\models\ElementFilter->validateSettings('settings', NULL, Object(yii\validators\InlineValidator))
#2 ../vendor/yiisoft/yii2/validators/InlineValidator.php(72): call_user_func(Array, 'settings', NULL, Object(yii\validators\InlineValidator))
#3 ../vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\InlineValidator->validateAttribute(Object(fruitstudios\searchit\models\ElementFilter), 'settings')
#4 ../vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(fruitstudios\searchit\models\ElementFilter), Array)
#5 ../vendor/fruitstudios/searchit/src/services/ElementFilters.php(308): yii\base\Model->validate()
#6 ../vendor/fruitstudios/searchit/src/migrations/m190204_000001_source_to_uids.php(65): fruitstudios\searchit\services\ElementFilters->saveElementFilter(Object(fruitstudios\searchit\models\ElementFilter))
#7 ../vendor/fruitstudios/searchit/src/migrations/m190204_000001_source_to_uids.php(22): fruitstudios\searchit\migrations\m190204_000001_source_to_uids->_sourcesToUid()
#8 ../vendor/craftcms/cms/src/db/Migration.php(56): fruitstudios\searchit\migrations\m190204_000001_source_to_uids->safeUp()
#9 ../vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#10 ../vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(fruitstudios\searchit\migrations\m190204_000001_source_to_uids))
#11 ../vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#12 ../vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#13 ../vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#14 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#15 ../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 ../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 ../vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#18 ../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#19 ../vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#20 ../vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#21 ../vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#22 ../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 ../web/index.php(21): yii\base\Application->run()
#24 {main}
```

**Comment by samhibberd** [comment]
Fixed in 1.0.6
