### ISSUE TITLE
Twig Runtime Error on plugin activation

### ISSUE THREAD

**Issue by Saboteur777** [fruitstudios/craft-searchit#15]
When I enable the plugin, I receive the following error:  

`Key "licenseIssues" for array with keys "developer, developerUrl, description, documentationUrl, class, basePath, aliases, name, version, changelogUrl, hasCpSettings, hasCpSection, packageName, isInstalled, isEnabled, moduleId, licenseKey, licenseKeyStatus, hasIssues, licenseStatusMessage" does not exist.`

The URL is `/admin/searchit/about`. 

```
Twig_Error_Runtime: Key "licenseIssues" for array with keys "developer, developerUrl, description, documentationUrl, class, basePath, aliases, name, version, changelogUrl, hasCpSettings, hasCpSection, packageName, isInstalled, isEnabled, moduleId, licenseKey, licenseKeyStatus, hasIssues, licenseStatusMessage" does not exist. in /var/www/vendor/fruitstudios/searchit/src/templates/about.twig:29
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Array, 'licenseIssues', Array, 'any', false, false)
#1 /var/www/storage/runtime/compiled_templates/22/22154f8bcf54d2c66f51600bc34424164fdb0a1ed702d6b9a25ec556b5aa2d9f.php(93): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Array, 'licenseIssues', Array)
#2 /var/www/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_92de4b11606aa8ba899ebcd72c5f8fc5b21af2f3690842bb3bdcba8397eff40f->block_content(Array, Array)
#3 /var/www/storage/runtime/compiled_templates/86/86f6c2e6c05d9fb4f1baf15d3162b9ebbc03c6f3e7541d758514fd8eaeed0f34.php(648): Twig_Template->displayBlock('content', Array, Array)
#4 /var/www/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_e0aa6a4766465b0d9d7e40424ddc13ac8dec04e51a334aff917d1067fb98bf8e->block_main(Array, Array)
#5 /var/www/storage/runtime/compiled_templates/86/86f6c2e6c05d9fb4f1baf15d3162b9ebbc03c6f3e7541d758514fd8eaeed0f34.php(533): Twig_Template->displayBlock('main', Array, Array)
#6 /var/www/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_e0aa6a4766465b0d9d7e40424ddc13ac8dec04e51a334aff917d1067fb98bf8e->block_body(Array, Array)
#7 /var/www/storage/runtime/compiled_templates/7f/7fcadaacaffa15219045ac6c16191136c7b3dcc16f060f83ebd16a58779ad457.php(60): Twig_Template->displayBlock('body', Array, Array)
#8 /var/www/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_158253132a267d8de121717a0b8d90916fdb58fa7f067cae62e1d9b33b35ffd8->doDisplay(Array, Array)
#9 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#10 /var/www/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#12 /var/www/storage/runtime/compiled_templates/69/693983d042eeceabfff17853a51bc5664042be3c8dfc2ddaad79d9258bf7cada.php(40): craft\web\twig\Template->display(Array, Array)
#13 /var/www/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_fb3c4d55246cd028097a0ffafc0c3afb8925db9fa617973d9db735bb044f67ca->doDisplay(Array, Array)
#14 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /var/www/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#17 /var/www/storage/runtime/compiled_templates/86/86f6c2e6c05d9fb4f1baf15d3162b9ebbc03c6f3e7541d758514fd8eaeed0f34.php(95): craft\web\twig\Template->display(Array, Array)
#18 /var/www/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_e0aa6a4766465b0d9d7e40424ddc13ac8dec04e51a334aff917d1067fb98bf8e->doDisplay(Array, Array)
#19 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /var/www/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#22 /var/www/storage/runtime/compiled_templates/20/2043d8b3c417851fb5728628266758e4b8a50963646b1508e6ba29a54cf406fc.php(32): craft\web\twig\Template->display(Array, Array)
#23 /var/www/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_347bc174fceca612c808d9d59d39c09f544ddbc28c3de797a60f8f556ff20ca2->doDisplay(Array, Array)
#24 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#25 /var/www/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#26 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#27 /var/www/storage/runtime/compiled_templates/44/446fc1ec656a018dbe2390bb17765e448ee8c9c28707e350ffa32cd135a88a9b.php(37): craft\web\twig\Template->display(Array, Array)
#28 /var/www/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_3a570a04b1052b605e068add534a36930112007a2e272807f7946315ff2e7950->doDisplay(Array, Array)
#29 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#30 /var/www/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#31 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#32 /var/www/storage/runtime/compiled_templates/22/22154f8bcf54d2c66f51600bc34424164fdb0a1ed702d6b9a25ec556b5aa2d9f.php(31): craft\web\twig\Template->display(Array, Array)
#33 /var/www/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_92de4b11606aa8ba899ebcd72c5f8fc5b21af2f3690842bb3bdcba8397eff40f->doDisplay(Array, Array)
#34 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#35 /var/www/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#36 /var/www/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#37 /var/www/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#38 /var/www/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#39 /var/www/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('searchit/about', Array)
#40 /var/www/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('searchit/about', Array)
#41 /var/www/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('searchit/about', Array)
#42 /var/www/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('searchit/about', Array)
#43 [internal function]: craft\controllers\TemplatesController->actionRender('searchit/about', Array)
#44 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#45 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#46 /var/www/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('render', Array)
#47 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#48 /var/www/vendor/craftcms/cms/src/web/Application.php(284): yii\base\Module->runAction('templates/rende...', Array)
#49 /var/www/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#50 /var/www/vendor/craftcms/cms/src/web/Application.php(273): yii\web\Application->handleRequest(Object(craft\web\Request))
#51 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#52 /var/www/web/index.php(21): yii\base\Application->run()
#53 {main}
```

**Comment by samhibberd** [comment]
@Saboteur777 can you confirm which versions of Craft & Searchit you are running?

**Comment by Saboteur777** [comment]
@samhibberd Sure: 

Craft 3.0.41.1
Searchit 1.0.3

**Comment by samhibberd** [comment]
So this is due to some changes Craft made to in the `getPluginInfo()` and me not adding the correct craft version requirement to Searchit. If you can't update to Craft 3.1.x, then asking craft get Searchit version 1.0.2 in your project composer file will fix it.

**Comment by Saboteur777** [comment]
Thanks, will update to 3.1 then.
